name: Initiate Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag"
        required: true
        default: "v0.0.1"
      name:
        description: "Name"
        required: true
        default: "Refyne"
      body:
        description: "Body"
        required: true
        default: " "

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "Refyne.ps1"
          tag: ${{ github.event.inputs.tag }}
          name: ${{ github.event.inputs.name }}
          body: ${{ github.event.inputs.body }}
