name: Create a new release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag"
        required: true
        default: "v0.0.1"
      name:
        description: "Name"
        required: true
        default: "Refyne"
      body:
        description: "Body"
        required: true
        default: " "

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: Refyne.ps1
          tag_name: ${{ github.event.inputs.tag }}
          name: ${{ github.event.inputs.name }}
          body: ${{ github.event.inputs.body }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
